# Generated by Django 4.2.7 on 2023-12-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='image',
            field=models.ImageField(default=None, upload_to='images/%Y/%m/%d', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
