# Generated by Django 4.2.7 on 2023-12-21 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date_of_start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата начала турнира'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('Не начат', 'Nostart'), ('Идёт', 'Processing'), ('Завершён', 'Сompleted')], default='Не начат', max_length=50, verbose_name='Статус'),
        ),
    ]
