# Generated by Django 4.2.7 on 2023-12-21 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_date_of_start_tournament_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tournament_referee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentreferee', verbose_name='Судья партии'),
            preserve_default=False,
        ),
    ]
