# Generated by Django 4.2.7 on 2023-12-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_game_tournament_referee'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.IntegerField(null=True, verbose_name='Счёт'),
        ),
    ]
