# Generated by Django 4.2.7 on 2023-12-21 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournamentimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='organizer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='tournaments.organizer'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='tournaments.player'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referee', to='tournaments.referee'),
        ),
    ]
